name: HISQIS Checker

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check-hisqis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run HISQIS Checker
        env:
          HISQIS_USERNAME: ${{ pegr252f }}
          HISQIS_PASSWORD: ${{ Tomcatpedro16(#) }}
          PUSHOVER_USER_KEY: ${{ uz8oohkxg7kvp3bzjphb914dkxe4ke }}
          PUSHOVER_API_TOKEN: ${{ asunz61ys4dn6efcctdkaa3w9xshxw }}
        run: |
          python hisqis_checker.py