{\rtf1\ansi\ansicpg1252\cocoartf2761
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: HISQIS Checker\
\
on:\
  schedule:\
    - cron: "*/15 * * * *"  # alle 15 Minuten\
  workflow_dispatch:        # manuell ausl\'f6sbar\
\
jobs:\
  check:\
    runs-on: ubuntu-latest\
\
    steps:\
    - name: Repository klonen\
      uses: actions/checkout@v3\
\
    - name: Python einrichten\
      uses: actions/setup-python@v4\
      with:\
        python-version: '3.11'\
\
    - name: Abh\'e4ngigkeiten installieren\
      run: |\
        pip install -r requirements.txt\
\
    - name: HISQIS Checker starten\
      env:\
        HISQIS_USERNAME: $\{\{ pegr252f \}\}\
        HISQIS_PASSWORD: $\{\{ Tomcatpedro16(#) \}\}\
        PUSHOVER_USER_KEY: $\{\{ uz8oohkxg7kvp3bzjphb914dkxe4ke \}\}\
        PUSHOVER_API_TOKEN: $\{\{ asunz61ys4dn6efcctdkaa3w9xshxw \}\}\
      run: |\
        python hisqis_checker.py\
}